#!/usr/bin/env python3
# Extract RPG Maker VX Ace Scripts.rvdata2 (Ruby Marshal 4.8 dump of an Array of
# [section_id:Integer, name:String, deflated_code:String]) into readable .rb files.
import sys, os, zlib, re

class MarshalReader:
    def __init__(self, data):
        self.d = data
        self.i = 0
        self.symbols = []
    def byte(self):
        b = self.d[self.i]; self.i += 1; return b
    def long(self):
        # Ruby Marshal packed integer. First byte is a SIGNED int8.
        c = self.byte()
        if c >= 128: c -= 256              # interpret as signed int8
        if c == 0: return 0
        if 1 <= c <= 4:                    # c bytes follow, positive
            val = 0
            for k in range(c):
                val |= self.byte() << (8*k)
            return val
        if -4 <= c <= -1:                  # -c bytes follow, negative
            n = -c; val = 0
            for k in range(n):
                val |= self.byte() << (8*k)
            return val - (1 << (8*n))
        if c > 0:  return c - 5            # 5..122 -> small positive 0..117
        return c + 5                        # -5..-123 -> small negative
    def string_raw(self):
        n = self.long()
        s = self.d[self.i:self.i+n]; self.i += n
        return s
    def parse(self):
        typ = chr(self.byte())
        if typ == '[':
            n = self.long()
            return [self.parse() for _ in range(n)]
        if typ == 'i':
            return self.long()
        if typ == 'I':   # ivar-wrapped object (string with encoding)
            obj = self.parse()
            nv = self.long()
            for _ in range(nv):
                self.parse()   # symbol key
                self.parse()   # value
            return obj
        if typ == '"':   # raw string
            return self.string_raw()
        if typ == ':':   # symbol
            s = self.string_raw(); self.symbols.append(s); return ('sym', s)
        if typ == ';':   # symlink
            idx = self.long(); return ('sym', self.symbols[idx])
        if typ == 'T': return True
        if typ == 'F': return False
        if typ == '0': return None
        if typ == 'l':  # bignum
            sign = chr(self.byte()); n = self.long(); raw = self.d[self.i:self.i+n*2]; self.i += n*2
            val = int.from_bytes(raw, 'little'); return val if sign=='+' else -val
        raise ValueError(f"unhandled marshal type {typ!r} at {self.i}")

def main():
    src = r"E:\Projects\RMProject\Data\Scripts.rvdata2"
    out = r"E:\Projects\RGSS-Godot\docs\rmva-scripts"
    os.makedirs(out, exist_ok=True)
    data = open(src, 'rb').read()
    assert data[0] == 4 and data[1] == 8, "not a Marshal 4.8 stream"
    mr = MarshalReader(data); mr.i = 2
    arr = mr.parse()
    print(f"sections: {len(arr)}")
    index_lines = []
    used = {}
    for pos, entry in enumerate(arr):
        sid, name, comp = entry
        if isinstance(name, bytes):
            name = name.decode('utf-8', 'replace')
        try:
            code = zlib.decompress(comp)
        except Exception as e:
            code = b"# <decompress failed: %s>" % str(e).encode()
        text = code.decode('utf-8', 'replace')
        safe = re.sub(r'[^A-Za-z0-9_\-]+', '_', name).strip('_') or 'unnamed'
        base = f"{pos:03d}_{safe}"
        if base in used:
            used[base] += 1; base = f"{base}_{used[base]}"
        else:
            used[base] = 0
        fn = base + ".rb"
        with open(os.path.join(out, fn), 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        index_lines.append(f"{pos:03d}\t{name}\t{fn}\t({len(text)} chars)")
    with open(os.path.join(out, "_INDEX.txt"), 'w', encoding='utf-8', newline='\n') as f:
        f.write("RPG Maker VX Ace Scripts.rvdata2 -- decompiled sections\n")
        f.write("Generated by tools/extract_scripts.py. DO NOT EDIT (regenerate instead).\n\n")
        f.write("\n".join(index_lines) + "\n")
    print(f"wrote {len(arr)} files to {out}")

if __name__ == "__main__":
    main()
